# Homological Quantum Rotor Codes

In this notebook we use sage to look at examples of homological quantum rotor codes as introduced in [arXiv:2303.13723](https://arxiv.org/abs/2303.13723)

## Real Projective Plane with Four Quantum Rotors
First look at the example of the real projective plane with four quantum rotors, $\mathbb{R}P^2(4)$, as drawn here:

<img src=projective-plane-4.png alt="Real Projective Plane" title="Real Projective Plane" width=200/>

We define the $H_X$ matrix from the faces and $H_Z$ from the vertices which yields


In [1]:
HX_RP = matrix(ZZ, [[+1, -1, 0, 0],
                    [0, 0, -1, +1],
                    [-1, -1, +1, +1]])
HZ_RP = matrix(ZZ, [[+1, +1, +1, +1],
                    [-1, -1, -1, -1]])

We can check that the matrices multiply to zero

In [2]:
HX_RP*HZ_RP.transpose()

[0 0]
[0 0]
[0 0]

Then we build the corresponding chain complex

In [3]:
RP = ChainComplex({1: HZ_RP, 2:HX_RP.transpose()}, degree_of_differential=-1)
pretty_print(RP)
pretty_print('d_1 = ', RP.differential(1))
pretty_print('d_2 = ', RP.differential(2))

Chain complex with at most 3 nonzero terms over Integer Ring

'd_1 = ' [ 1  1  1  1]
[-1 -1 -1 -1]

'd_2 = ' [ 1  0 -1]
[-1  0 -1]
[ 0 -1  1]
[ 0  1  1]

Sage can compute the integer homology and cohomology at every level ('C2' designate the cyclic group of order 2)

In [4]:
print('Homology:\t{}\n'.format(RP.homology()))
print('Cohomology:\t{}'.format(RP.dual().homology()))

Homology:	{0: Z, 1: C2, 2: 0}

Cohomology:	{0: Z, 1: 0, 2: C2}


Sage can also compute the (co)homology over any field (we just look at level 1 here)

In [5]:
print('Level 1 cohomology over Z:\t{}\n'.format(RP.dual().homology()[1]))
print('Level 1 cohomology over F_2:\t{}\n'.format(RP.dual().homology(base_ring=GF(2))[1]))
print('Level 1 cohomology over F_3:\t{}\n'.format(RP.dual().homology(base_ring=GF(3))[1]))
print('Level 1 cohomology over Q:\t{}\n'.format(RP.dual().homology(base_ring=QQ)[1]))

Level 1 cohomology over Z:	0

Level 1 cohomology over F_2:	Vector space of dimension 1 over Finite Field of size 2

Level 1 cohomology over F_3:	Vector space of dimension 0 over Finite Field of size 3

Level 1 cohomology over Q:	Vector space of dimension 0 over Rational Field



We can also compute the generators of the (co)homology

In [6]:
print('Homology(RP, Z):\t{}\n'.format(RP.homology()[1]))
print('Generator:\t{}\n'.format(RP.homology(generators=True)[1][0][1].vector(1)))
print('Cohomology(RP, Z_2):\t{}\n'.format(RP.dual().homology(base_ring=GF(2))[1]))
print('Generator:\t{}'.format(RP.dual().homology(base_ring=GF(2), generators=True)[1][0][1].vector(1)))

Homology(RP, Z):	C2

Generator:	(0, -1, 1, 0)

Cohomology(RP, Z_2):	Vector space of dimension 1 over Finite Field of size 2

Generator:	(0, 0, 1, 1)


## Thin Möbius Strip
We look now at the thin Möbius strip with rough boundaries as drawn here:

<img src=thin_moebius_strip.png alt="Möbius strip" title="Möbius strip" width=600/>

We pick $N=3$ and define again the $H_X$ matrix from the faces and $H_Z$ from the vertices which yields


In [7]:
HX_TM = matrix(ZZ, [[1, -1, 0, -1, 1, 0],
                    [0, 1, -1, 0, -1, 1],
                    [1, 0, 1, -1, 0, -1]])
HZ_TM = matrix(ZZ, [[1, 0, 0, 1, 0, 0],
                    [0, 1, 0, 0, 1, 0],
                    [0, 0, 1, 0, 0, 1]])

TM = ChainComplex({1: HZ_TM, 2:HX_TM.transpose()}, degree_of_differential=-1)
pretty_print(TM)

Chain complex with at most 3 nonzero terms over Integer Ring

We check the homology and cohomology and find a logical qubit

In [8]:
print('Homology(TM, Z):\t{}\n'.format(TM.homology()[1])) 
print('Generator:\t{}\n'.format(TM.homology(generators=True)[1][0][1].vector(1)))
print('Cohomology(TM, Z_2):\t{}\n'.format(TM.dual().homology(base_ring=GF(2))[1]))
print('Generator:\t{}'.format(TM.dual().homology(base_ring=GF(2), generators=True)[1][0][1].vector(1)))

Homology(TM, Z):	C2

Generator:	(0, 0, 1, 0, 0, -1)

Cohomology(TM, Z_2):	Vector space of dimension 1 over Finite Field of size 2

Generator:	(0, 0, 0, 1, 1, 1)


## Thin Cylinder
If we remove the twist from the previous example we get a cylinder encoding a rotor.
To remove the twist we just change the signs of the last plaquette.

In [9]:
HX_C = matrix(ZZ, [[1, -1, 0, -1, 1, 0],
                   [0, 1, -1, 0, -1, 1],
                   [-1, 0, 1, 1, 0, -1]])
HZ_C = matrix(ZZ, [[1, 0, 0, 1, 0, 0],
                   [0, 1, 0, 0, 1, 0],
                   [0, 0, 1, 0, 0, 1]])

C = ChainComplex({1: HZ_C, 2:HX_C.transpose()}, degree_of_differential=-1)
pretty_print(C)

Chain complex with at most 3 nonzero terms over Integer Ring

In [10]:
print('Homology(C, Z):\t{}'.format(C.homology()[1]))
print('\nGenerator:\t{}'.format(C.homology(generators=True)[1][0][1].vector(1)))
print('\nCohomology(C, Z):\t{}'.format(C.dual().homology()[1]))
print('\nGenerator:\t{}'.format(C.dual().homology(generators=True)[1][0][1].vector(1)))

Homology(C, Z):	Z

Generator:	(1, 0, 0, -1, 0, 0)

Cohomology(C, Z):	Z

Generator:	(1, 0, 0, 0, -1, -1)


## Torus
We can check that the torus in 2D has two logical rotors

In [11]:
T2 = simplicial_complexes.Torus().chain_complex()
pretty_print(T2)
print('Homology(T2, Z):\t {}'.format(T2.homology()[1]))

Chain complex with at most 3 nonzero terms over Integer Ring

Homology(T2, Z):	 Z x Z


## 3D Real Projective Space
We can also check that the real projective space in 3D encodes a single qubit
<img src=RP3.png alt="Real Projective Space" title="Real Projective Space" width=200/>


In [12]:
RP3 = simplicial_complexes.RealProjectiveSpace(3).chain_complex()
pretty_print(RP3)
print('Homology(RP3, Z):\t{}'.format(RP3.homology()[1]))
print('Cohomology(RP3, Z_2):\t{}'.format(RP3.dual().homology(base_ring=GF(2))[1]))

Chain complex with at most 4 nonzero terms over Integer Ring

Homology(RP3, Z):	C2
Cohomology(RP3, Z_2):	Vector space of dimension 1 over Finite Field of size 2


## Product of Chain Complexes
We now look at getting quantum rotor codes from product of chain complexes. Starting from matrices seen as chain complexes of length two we get chain complexes of length three by taking the product.

In [13]:
import numpy as np
import numpy.random as rd
import numpy.linalg as nplg

def random_binary_code(n, k, w):
    H = np.zeros((n - k, n), dtype='int')
    for i in range(n - k):
        for j in range(n):
            if rd.rand() < w / n:
                H[i, j] = 1
    return H

def product_from_M(M1, M2):
    C1 = ChainComplex({1:M1}, degree_of_differential=-1)
    C2 = ChainComplex({1:M2}, degree_of_differential=-1)
    return C1.tensor(C2)

Take the parity check matrix from the Hamming code, and look at it as a length two chain complex, it has free homology.

In [14]:
Ham = matrix(ZZ, [[1, 1, 1, 0, 0, 1, 0],
                  [0, 1, 1, 1, 0, 0, 1],
                  [1, 0, 1, 1, 1, 0, 0]])

CC_Ham = ChainComplex({1: Ham}, degree_of_differential=-1)

pretty_print(CC_Ham)

print('Homology(Ham, Z):\t{}'.format(CC_Ham.homology()))

G = np.array([g[1].vector(1) for g in CC_Ham.homology(generators=True)[1][:]])
print('\nGenerators (G):\n {}'.format(G))

print('\nCohomology(Ham, Z):\t{}'.format(CC_Ham.dual().homology()))

E = np.array([g[1].vector(1) for g in CC_Ham.dual().homology(generators=True)[1][:]])
print('\nGenerators (E):\n {}'.format(E))

Chain complex with at most 2 nonzero terms over Integer Ring

Homology(Ham, Z):	{0: 0, 1: Z x Z x Z x Z}

Generators (G):
 [[ 1  0  0  0 -1 -1  0]
 [ 0  1  0  0  0 -1 -1]
 [ 0  0  1  0 -1 -1 -1]
 [ 0  0  0  1 -1  0 -1]]

Cohomology(Ham, Z):	{0: 0, 1: Z x Z x Z x Z}

Generators (E):
 [[1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1]]


Look at the square symetric matrix obtained from the Hamming parity check matrix: SHam = Ham^T Ham. As a length two chain complex it has only torsion homology.

In [15]:
SHam = Ham.transpose()*Ham % 2
pretty_print(SHam)

CC_SHam = ChainComplex({1: SHam}, degree_of_differential=-1)

pretty_print(CC_SHam)

print('\nHomology(SHam, Z):\t{}'.format(CC_SHam.homology()))

Eprime = np.array([g[1].vector(0) for g in CC_SHam.homology(generators=True)[0][:]])
print('\nGenerators (Eprime):\n {}'.format(Eprime))


[0 1 0 1 1 1 0]
[1 0 0 1 0 1 1]
[0 0 1 0 1 1 1]
[1 1 0 0 1 0 1]
[1 0 1 1 1 0 0]
[1 1 1 0 0 1 0]
[0 1 1 1 0 0 1]

Chain complex with at most 2 nonzero terms over Integer Ring


Homology(SHam, Z):	{0: C2 x C2 x C2 x C4, 1: 0}

Generators (Eprime):
 [[0 0 0 1 0 0 1]
 [0 0 0 0 1 0 1]
 [0 0 0 0 0 1 1]
 [0 0 0 0 0 0 1]]


### Free+Free Product: Logical Rotors
We can now look at products, starting with a product with only free homology yielding a quantum rotor code encoding logical rotors

In [16]:
FF = product_from_M(Ham, Ham.transpose())
print('Homology(FF, Z):\t{}'.format(FF.homology()[1]))

Homology(FF, Z):	Z^16


### Free+Torsion Product
The product of free homology with torsion keeps the torsion, it gives a quantum rotor codes encoding logical qudits

In [17]:
FT = product_from_M(Ham, SHam)
print('Homology(FT, Z):\t{}'.format(FT.homology()[1]))

Homology(FT, Z):	C2^12 x C4 x C4 x C4 x C4


### Torsion+Torsion Product
The product of torsion with torsion keeps only the common torsion

In [18]:
TT = product_from_M(SHam, SHam)
print('Homology(TT, Z):\t{}'.format(TT.homology()[1]))

Homology(TT, Z):	C2^15 x C4


### Random matrices

We can do the same by first picking the initial classical binary code at random.

In [19]:
m = 18
w = 5

rankMrand = 0
while rankMrand < m:
    Hrand = random_binary_code(m,int(m/3),w)
    Mrand = (Hrand.transpose()@Hrand % 2)
    rankMrand = nplg.matrix_rank(Mrand)

We check that the rectangular parity check matrix exhibits free homology.

In [20]:
CC_Hrand = ChainComplex({1: Matrix(ZZ, Hrand)}, degree_of_differential=-1)

pretty_print(CC_Hrand)

print('Homology(Hrand, Z):\t{}'.format(CC_Hrand.homology()))

print('\nCohomology(Hrand, Z):\t{}'.format(CC_Hrand.dual().homology()))

Chain complex with at most 2 nonzero terms over Integer Ring

Homology(Hrand, Z):	{0: 0, 1: Z^6}

Cohomology(Hrand, Z):	{0: 0, 1: Z^6}


We also check that the corresponding square matrix has only torsion

In [21]:
CC_Mrand = ChainComplex({1: Matrix(ZZ, Mrand)}, degree_of_differential=-1)

pretty_print(CC_Mrand)

print('Homology(SHam, Z): {}'.format(CC_Mrand.homology()))


Chain complex with at most 2 nonzero terms over Integer Ring

Homology(SHam, Z): {0: C2^5 x C28, 1: 0}


### Free+Free Product

In [22]:
FFrand = product_from_M(Matrix(ZZ, Hrand), Matrix(ZZ, Hrand.transpose()))
pretty_print(FFrand)
print('Homology(FFrand, Z): {}'.format(FFrand.homology()[1]))

Chain complex with at most 3 nonzero terms over Integer Ring

Homology(FFrand, Z): Z^36


### Free+Torsion Product

In [23]:
FTrand = product_from_M(Matrix(ZZ, Hrand), Matrix(ZZ, Mrand))
pretty_print(FTrand)
print('Homology(FTrand, Z): {}'.format(FTrand.homology()[1]))

Chain complex with at most 3 nonzero terms over Integer Ring

Homology(FTrand, Z): C2^30 x C28^6


### Torsion+Torsion Product

In [24]:
rankMrand2 = 0
while rankMrand2 < m:
    Hrand2 = random_binary_code(m,int(m/3),w)
    Mrand2 = (Hrand2.transpose()@Hrand2 % 2)
    rankMrand2 = nplg.matrix_rank(Mrand2)

CC_Mrand2 = ChainComplex({1: Matrix(ZZ, Mrand2)}, degree_of_differential=-1)

pretty_print(CC_Mrand2)

print('Homology(Mrand2, Z): {}'.format(CC_Mrand2.homology()))

TTrand = product_from_M(Matrix(ZZ, Mrand), Matrix(ZZ, Mrand2))
pretty_print(TTrand)
print('Homology(TTrand, Z): {}'.format(TTrand.homology()[1]))

Chain complex with at most 2 nonzero terms over Integer Ring

Homology(Mrand2, Z): {0: C2^5 x C102, 1: 0}


Chain complex with at most 3 nonzero terms over Integer Ring

Homology(TTrand, Z): C2^36
